### ISSUE TITLE
Endpoint to query all users that called X function 

### ISSUE THREAD

**Issue by idea404** [telezhnaya/near_enhanced_api#2]
Had a query from a dev in Office Hours that wanted to query all account IDs that called a smart contract function

Would be nice to have a generic possibility, so making specifying smart contract in this query optional as to allow ecosystem-wide queries

**Comment by frol** [comment]
@idea404 Do we know why they needed it? In general case we may expect millions of accounts to call some function name, so I would avoid having such API endpoint even with pagination since without extra filters it won't be useful, but if we add filters, we step into the space of Data Warehouse which would allow users to make arbitrary complex queries

**Comment by idea404** [comment]
@frol I recall the most recent use case being querying all accounts that called the `nft_mint` function of a given contract. Although the standard implements a `nft_tokens` function that grants information on all NFTs pertaining to that contract, this dev wanted to know all accounts that originally minted NFTs. 

Considering how intensive this query could become, we might want to limit the query itself to provide 1 contract for this call (and perhaps add some time-bound filters additionally?). It would then be up to the developer to determine what contracts to perform this query on.

**Comment by frol** [comment]
@idea404 As I expected, it is xy-problem, and we actually will provide extensive APIs for NFTs (including those that predate JSON Events standard)
